name: 'Pointer'
description: 'This action is used to point to another action'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    
    - if: contains(github.event.repository.topics, 'docker')
      uses: demo-hell/reusable-pipelines/.github/workflows/pipe-docker-image.yml@main
    
    - if: contains(github.event.repository.topics, 'another-topic')
      uses: demo-hell/reusable-pipelines/.github/workflows/pipe-other.yml@main

# jobs:
#   pointer-pipe-docker-image:
#     if: contains(github.event.repository.topics, 'docker')
#     uses: demo-hell/reusable-pipelines/.github/workflows/pipe-docker-image.yml@main
#     secrets: inherit

#   another-job:
#     if: contains(github.event.repository.topics, 'another-topic')
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#       - name: Run another job
#         run: echo "Running another job based on the topic"