name: pointer

on:
  push:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: demo-hell/reusable-pipelines/.github/actions/pointer@main
        with:
          secrets: inherit
    